=== alxjrvs/SU-SRD/packages/salvageunion-reference/schemas/bio-titans.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://salvageunion.com/schemas/bio-titans.schema.json",
  "title": "bio-titans",
  "description": "Massive bio-engineered titan creatures in Salvage Union",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["structurePoints", "actions"],
    "properties": {
      "asset_url": {
        "$ref": "shared/common.schema.json#/definitions/asset_url"
      },
      "content": {
        "$ref": "shared/objects.schema.json#/definitions/content"
      },
      "id": {
        "$ref": "shared/common.schema.json#/definitions/id"
      },
      "indexable": {
        "type": "boolean",
        "default": true
      },
      "blackMarket": {
        "type": "boolean",
        "default": false
      },
      "name": {
        "$ref": "shared/common.schema.json#/definitions/name"
      },
      "source": {
        "$ref": "shared/enums.schema.json#/definitions/source"
      },
      "page": {
        "$ref": "shared/common.schema.json#/definitions/positiveInteger"
      },
      "structurePoints": {
        "$ref": "shared/common.schema.json#/definitions/positiveInteger"
      },
      "actions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "traits": {
        "type": "array",
        "description": "Special traits and properties of items, systems, or abilities",
        "items": {
          "$ref": "shared/objects.schema.json#/definitions/trait"
        }
      }
    },
    "additionalProperties": false
  }
}

=== alxjrvs/SU-SRD/packages/salvageunion-reference/data/bio-titans.json
[
  {
    "id": "8e5b04e5-9532-48c1-86ae-5960da416ede",
    "source": "Salvage Union Workshop Manual",
    "name": "Scylla",
    "actions": [
      "Scythe Attack",
      "Tail Sweep",
      "Climb",
      "Armour Plating (Scylla)",
      "Ambush Predator",
      "Titanic Actions (Scylla)"
    ],
    "structurePoints": 39,
    "asset_url": "https://opxrguskxuogghzcnppk.supabase.co/storage/v1/object/public/LP-Assets/bio-titans/scylla.jpg",
    "page": 276,
    "content": [
      {
        "type": "paragraph",
        "value": "A gigantic, armoured, arachnid-like predator beast. It has no concept that the war it was designed to fight ended aeons ago, and continues to tear apart anything that enters into its mountainous domain."
      }
    ]
  },
  {
    "id": "8bab65a1-d9ee-445e-97d6-9d13602831ee",
    "source": "Salvage Union Workshop Manual",
    "name": "Typhon",
    "actions": [
      "Burrower",
      "Armour Plating (Typhon)",
      "Swallow Whole",
      "Spiked Carapace",
      "Titanic Actions (Typhon)"
    ],
    "structurePoints": 67,
    "asset_url": "https://opxrguskxuogghzcnppk.supabase.co/storage/v1/object/public/LP-Assets/bio-titans/typhon.jpg",
    "page": 278,
    "content": [
      {
        "type": "paragraph",
        "value": "Vengeance of the earth. This terrifying spiked worm can even swallow a Colossus whole. Some believe the spirits of miners in the Ferrous Range, who died in industrial accidents, summoned this being in vengeance."
      }
    ]
  },
  {
    "id": "a6cc074f-2e23-48d0-8448-4825d803d153",
    "source": "Salvage Union Workshop Manual",
    "name": "Chrysalis",
    "actions": [
      "Flying",
      "Cluster Energy Bombs",
      "Entrancing Song",
      "Cocoon",
      "Birth Pods",
      "Titanic Actions (Chrysalis)"
    ],
    "structurePoints": 80,
    "asset_url": "https://opxrguskxuogghzcnppk.supabase.co/storage/v1/object/public/LP-Assets/bio-titans/chrysalis.jpg",
    "page": 280,
    "content": [
      {
        "type": "paragraph",
        "value": "A mammoth flying insect with a wingspan the size of a city and an entrancing song that captures the souls of mortals. Said to inhabit a cave in the Verdant Crescent, it is worshipped by the wastelanders who live there as a god."
      }
    ]
  },
  {
    "id": "9c548eba-0fbe-4eb5-8752-a0cfe4c319f9",
    "source": "Salvage Union Workshop Manual",
    "name": "Phantom",
    "actions": ["Nether Teleport", "Phasic Core", "Morph Scythes", "Titanic Actions (Phantom)"],
    "structurePoints": 54,
    "asset_url": "https://opxrguskxuogghzcnppk.supabase.co/storage/v1/object/public/LP-Assets/bio-titans/phantom.jpg",
    "page": 282,
    "content": [
      {
        "type": "paragraph",
        "value": "A multi-scythed being that can bend itself through reality. Rumoured to have been crafted in the Opus Institute Research Lab in the Frozen Gulf before breaking free to wreak havoc."
      }
    ]
  },
  {
    "id": "ba63bfa7-9e90-4c81-bcc6-90e4ddfac939",
    "source": "Salvage Union Workshop Manual",
    "name": "Electrophorus",
    "actions": [
      "Electrified Spines",
      "Static Field",
      "Hover",
      "Bio-Electric Arc",
      "Bio-Electric Shield",
      "Titanic Actions (Electrophorus)"
    ],
    "structurePoints": 96,
    "asset_url": "https://opxrguskxuogghzcnppk.supabase.co/storage/v1/object/public/LP-Assets/bio-titans/electrophorus.jpg",
    "page": 284,
    "content": [
      {
        "type": "paragraph",
        "value": "A vast, eel-like Bio-Titan able to harness bioelectric energy. Rumoured to dwell at the deepest point of the world's oceans within the Amara Trench in the Oceanic Rim."
      }
    ]
  },
  {
    "id": "a7952eaa-4621-4f4f-8944-ee249d9a04a3",
    "source": "Salvage Union Workshop Manual",
    "name": "Tyrant",
    "actions": [
      "Claw Swipes",
      "Amphibious",
      "Destroyer of Worlds",
      "Regeneration",
      "Tail Swat",
      "Rending Bite",
      "Irradiated Beam",
      "Titanic Actions (Tyrant)"
    ],
    "structurePoints": 215,
    "asset_url": "https://opxrguskxuogghzcnppk.supabase.co/storage/v1/object/public/LP-Assets/bio-titans/tyrant.jpg",
    "page": 286,
    "content": [
      {
        "type": "paragraph",
        "value": "A mammoth, amphibian lizard said to have been born in the aftermath of the first nuclear war. It dwells somewhere deep within The Great Cape and was responsible for the destruction of the Kombu Tech home arco, a coastal city of a million souls."
      }
    ]
  },
  {
    "id": "ab560707-8448-47be-9cfb-4dca5ead08c1",
    "source": "We Were Here First!",
    "name": "Cortex Bio-Titan",
    "actions": [
      "One Step Ahead (Cortex Bio-Titan)",
      "Proboscis (Cortex Bio-Titan)",
      "Mutant Fanatics (Cortex Bio-Titan)",
      "Probing Telepathy (Cortex Bio-Titan)",
      "Titanic Actions (Cortex Bio-Titan)"
    ],
    "structurePoints": 10,
    "page": 56,
    "content": [
      {
        "type": "paragraph",
        "value": "A Bio-Titan developed by the Red Mesa researchers to be hyper-intelligent. It resembles a bloated slug, with hundreds of tiny eyes and a huge tentacle-like proboscis protruding from its drooling mouth."
      }
    ]
  },
  {
    "id": "47373f75-5014-4549-a6de-b087dda6eedf",
    "source": "Rainmaker",
    "name": "Apophis",
    "actions": [
      "Camouflaged Scales (Apophis)",
      "Venomous Bite (Apophis)",
      "Constricting Coils (Apophis)",
      "Crush (Apophis)",
      "Titanic Actions (Apophis)"
    ],
    "structurePoints": 60,
    "page": 81,
    "content": [
      {
        "type": "paragraph",
        "value": "A mutated, snake-like Bio-Titan that can crush a Mech within its coiled flesh. Its scintillating scales throw off enemy targets and allow it to hide and wait in ambush for its prey."
      }
    ]
  },
  {
    "id": "4bfca8cc-9f66-489f-a002-74fbf4e47a21",
    "source": "Rainmaker",
    "page": 82,
    "name": "Hill Worm Pattern Typhon",
    "actions": [
      "Burrower",
      "Armour Plating (Typhon)",
      "Swallow Whole",
      "Spiked Carapace",
      "Titanic Actions (Typhon)"
    ],
    "structurePoints": 67,
    "content": [
      {
        "type": "paragraph",
        "value": "A bloated, heavily armoured, insatiably hungry worm that lurks beneath the Wild Hills."
      },
      {
        "type": "paragraph",
        "value": "Vengeance of the earth. This terrifying spiked worm can even swallow a Colossus whole. Some believe the spirits of miners in the Ferrous Range, who died in industrial accidents, summoned this being in vengeance."
      },
      {
        "type": "paragraph",
        "value": "Metallic Reconstitution: The Worm's physiology extracts metals and extrudes them as defensive rings. It gains an additional Armour Plating when it reduces a Mech or Vehicle to 0 SP."
      }
    ]
  },
  {
    "id": "3c81e43c-63f3-4072-ba1e-280111bf8f38",
    "name": "Genbu",
    "source": "Rainmaker",
    "page": 82,
    "structurePoints": 47,
    "actions": [
      "Aquatic Ambusher (Genbu)",
      "Grasping Tentacles (Genbu)",
      "Mace-Tentacles (Genbu)",
      "Shell Regeneration (Genbu)",
      "Armour Plating (Genbu)",
      "Cephalopod (Genbu)",
      "Titanic Actions (Genbu)"
    ],
    "content": [
      {
        "type": "paragraph",
        "value": "A hard, armoured shell that sprouts writhing tentacles that pummels its prey with sheer brute force, able to bludgeon steel with the sheer force of its mass. Lairs in an underwater environment where it can surprise its foes and drag them down to the depths to feed."
      }
    ]
  },
  {
    "id": "283e9165-721c-4543-8def-d6a88af366e3",
    "source": "Rainmaker",
    "name": "Physalis",
    "actions": [
      "Pilot Seeker Tendrils",
      "Puppeteer Tendrils",
      "Mech Marionette",
      "Puppet Shield",
      "Hovering Mass",
      "Titanic Actions (Physalis)"
    ],
    "structurePoints": 34,
    "page": 83,
    "content": [
      {
        "type": "paragraph",
        "value": "A sea of floating tendrils, Physalis is a Bio-Titan able to liquify a Pilot in their cockpit and turn their Mech into a marionette under its control. Its lair is surrounded by Mech carcasses and the liquified remains of their pilots."
      }
    ]
  }
]
