=== alxjrvs/SU-SRD/packages/salvageunion-reference/schemas/creatures.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://salvageunion.com/schemas/creatures.schema.json",
  "title": "creatures",
  "description": "Creatures and wildlife in Salvage Union",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["hitPoints", "actions"],
    "properties": {
      "asset_url": {
        "$ref": "shared/common.schema.json#/definitions/asset_url"
      },
      "content": {
        "$ref": "shared/objects.schema.json#/definitions/content"
      },
      "id": {
        "$ref": "shared/common.schema.json#/definitions/id"
      },
      "indexable": {
        "type": "boolean",
        "default": true
      },
      "blackMarket": {
        "type": "boolean",
        "default": false
      },
      "name": {
        "$ref": "shared/common.schema.json#/definitions/name"
      },
      "source": {
        "$ref": "shared/enums.schema.json#/definitions/source"
      },
      "page": {
        "$ref": "shared/common.schema.json#/definitions/positiveInteger"
      },
      "actions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "traits": {
        "type": "array",
        "items": {
          "$ref": "shared/objects.schema.json#/definitions/trait"
        }
      },
      "hitPoints": {
        "$ref": "shared/common.schema.json#/definitions/hitPoints"
      }
    },
    "additionalProperties": false
  }
}

=== alxjrvs/SU-SRD/packages/salvageunion-reference/data/creatures.json
[
  {
    "id": "ba8b32f2-3916-43d0-937d-74168b846114",
    "source": "Salvage Union Workshop Manual",
    "name": "Irradiated Scorpion",
    "actions": ["Stinger"],
    "hitPoints": 4,
    "page": 296,
    "content": [
      {
        "type": "paragraph",
        "value": "Mutated beyond their usual size, they have been known to kill entire camps of wasters."
      }
    ]
  },
  {
    "id": "204c855b-e13b-4326-9355-24be3a38ae34",
    "source": "Salvage Union Workshop Manual",
    "name": "Artl",
    "asset_url": "https://opxrguskxuogghzcnppk.supabase.co/storage/v1/object/public/LP-Assets/creatures/artl.jpg",
    "traits": [
      {
        "type": "burrower"
      }
    ],
    "actions": ["Acid Spit", "Corrosive Skin Glands"],
    "hitPoints": 2,
    "page": 266,
    "content": [
      {
        "type": "paragraph",
        "value": "Burrowing, ambush predators that liquify their prey for easier digestion."
      }
    ]
  },
  {
    "id": "6718545a-0261-4e4c-874c-079f1a9fcd80",
    "source": "Salvage Union Workshop Manual",
    "name": "Chimeripede",
    "asset_url": "https://opxrguskxuogghzcnppk.supabase.co/storage/v1/object/public/LP-Assets/creatures/chimeripede.jpg",
    "actions": ["Barbed Tentacles"],
    "hitPoints": 10,
    "page": 272,
    "content": [
      {
        "type": "paragraph",
        "value": "A mutated, radiation scarred amalgamation of flesh."
      }
    ]
  },
  {
    "id": "bfbf2664-6139-4727-8ad1-26ec1c01ae12",
    "source": "Salvage Union Workshop Manual",
    "name": "Wasteland Bear",
    "actions": ["Bear Carnage"],
    "hitPoints": 5,
    "page": 297,
    "content": [
      {
        "type": "paragraph",
        "value": "Large, hungry, and ferocious, these bears are not just after your picnic basket."
      }
    ]
  },
  {
    "id": "f32c1706-6bc0-476b-af22-01f0e4339034",
    "source": "Salvage Union Workshop Manual",
    "name": "Molebear",
    "asset_url": "https://opxrguskxuogghzcnppk.supabase.co/storage/v1/object/public/LP-Assets/creatures/molebear.jpg",
    "traits": [
      {
        "type": "burrower"
      }
    ],
    "actions": ["Iron Claw"],
    "hitPoints": 12,
    "page": 266,
    "content": [
      {
        "type": "paragraph",
        "value": "Terrifying, huge burrowing predators known to rend through metal."
      }
    ]
  },
  {
    "id": "9303ec5f-5cda-4edc-8ebf-265850bcdfcd",
    "source": "Salvage Union Workshop Manual",
    "name": "Carrion Bird",
    "traits": [
      {
        "type": "fly"
      }
    ],
    "actions": ["Talons"],
    "hitPoints": 3,
    "page": 266,
    "content": [
      {
        "type": "paragraph",
        "value": "Large flying scavengers that feast on flesh and bone."
      }
    ]
  },
  {
    "id": "46102100-e51b-48a1-9264-4025105d7c2b",
    "source": "Rainmaker",
    "page": 81,
    "name": "Basement Frogs",
    "actions": ["Pseudo-teeth", "Tongue Lash"],
    "hitPoints": 2,
    "content": [
      {
        "type": "paragraph",
        "value": "Territorial, these frogs have grown large and aggressive to defend their home. They use their tongues to trip and tangle their prey so that the rest can descend on them."
      },
      {
        "type": "paragraph",
        "value": "Ambush: Basement Frogs always act first in combat. If someone else has a similar Ability they act simultaneously."
      }
    ]
  },
  {
    "id": "7c9f8da0-7f31-429b-970e-5ec25d5fffef",
    "source": "Rainmaker",
    "name": "Ghost",
    "page": 81,
    "actions": ["Metal Bars and Ripping Hands (Ghost)"],
    "hitPoints": 4,
    "content": [
      {
        "type": "paragraph",
        "value": "Creatures of nightmares brought to life by biotechnology to rip and tear."
      },
      {
        "type": "paragraph",
        "value": "Phased: Ghosts are permanently phased. They can move through walls and obstacles and are invisible except for a faint blue outline. They can make attacks whilst phased. Thermal Optics will allow a Ghost to be seen in its phased state."
      },
      {
        "type": "paragraph",
        "value": "Organic: Ghosts are biological horrors. They are treated as creatures for the purposes of all Traits and Abilities, for example the Anti-Organic Trait (p.318 SU Core Book)."
      }
    ]
  },
  {
    "id": "e4c80ede-89d0-483e-8f9f-6b080287f5ad",
    "source": "Rainmaker",
    "name": "Ghost Haunt",
    "page": 81,
    "actions": ["Metal Bars and Ripping Hands (Ghost Haunt)"],
    "hitPoints": 12,
    "content": [
      {
        "type": "paragraph",
        "value": "A haunt of ghosts that sow terror and mayhem."
      },
      {
        "type": "paragraph",
        "value": "Phased: See Ghost."
      },
      {
        "type": "paragraph",
        "value": "Organic: See Ghost."
      }
    ]
  }
]
